/*
 * LCD.C
 *
 *  Created on: Feb 6, 2021
 *      Author: ahmed
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include"string.h"

#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "LCD_int.h"
#include "ADC_Interface.h"
#include "STK_interface.h"



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void delay_us(u32 copy_u32time)
{
	for(u32 i=0;i<copy_u32time;i++)
	{
		for(u16 j=0;j<565;j++)
		{
			asm("NOP");
		}
	}
}


u32 ahmed(void){
	u32 i=0;
	i++;
	return i;
}

static volatile u32 LDR =0;
static volatile u32 POT =0;
static volatile u32 inputVoltage =0;
static volatile u32 inputVoltage1 =0;

int main(void)
{

	u8 SHOWLDR [4];
	u8 SHOWPOT [4];


	RCC_voidInit();

	RCC_voidEnablePeripheralClock(RCC_APB2, RCC_GPIOA_ID);
	RCC_voidEnablePeripheralClock(RCC_APB2, RCC_ADC_ID);
	DIO_voidSetPinDirection(DIO_U8_PORTA,DIO_U8_PIN2, DIO_OUTPUT_2MHZ_PP);
	DIO_voidSetPinDirection(DIO_U8_PORTA,DIO_U8_PIN3, DIO_OUTPUT_2MHZ_PP);
	DIO_voidSetPinDirection(DIO_U8_PORTA,DIO_U8_PIN4, DIO_OUTPUT_2MHZ_PP);
	DIO_voidSetPinDirection(DIO_U8_PORTA,DIO_U8_PIN5, DIO_OUTPUT_2MHZ_PP);
	DIO_voidSetPinDirection(DIO_U8_PORTA,DIO_U8_PIN6, DIO_OUTPUT_2MHZ_PP);
	DIO_voidSetPinDirection(DIO_U8_PORTA,DIO_U8_PIN7, DIO_OUTPUT_2MHZ_PP);
	DIO_voidSetPinDirection(DIO_U8_PORTA,DIO_U8_PIN8, DIO_OUTPUT_2MHZ_PP);
	DIO_voidSetPinDirection(DIO_U8_PORTA,DIO_U8_PIN9, DIO_OUTPUT_2MHZ_PP);
	DIO_voidSetPinDirection(DIO_U8_PORTA,DIO_U8_PIN10, DIO_OUTPUT_2MHZ_PP);
	DIO_voidSetPinDirection(DIO_U8_PORTA,DIO_U8_PIN11, DIO_OUTPUT_2MHZ_PP);
	DIO_voidSetPinDirection(DIO_U8_PORTA,DIO_U8_PIN12, DIO_OUTPUT_2MHZ_PP);
	DIO_voidSetPinDirection(DIO_U8_PORTA,DIO_U8_PIN0, DIO_INPUT_ANALOG);
	DIO_voidSetPinDirection(DIO_U8_PORTA,DIO_U8_PIN1, DIO_INPUT_ANALOG);



	LCD_vidInit();
	ADC_voidInit();
	ADC_voidEnable();
	ADC_voidMode();
	ADC_voidResetCalAndCal();
	STK_voidInit();


	void ahmed2(void)
	{
		static u8 flag = 0;
		if(flag == 0)
		{
			flag = 1;

			LDR=Adc_voidReadADC(CH0,ADC_SampleTime_Cycles_5)/1;


			 inputVoltage = (LDR* 33) / 4096 ;

		}
		else if(flag == 1)
		{
			flag = 0;


			POT=Adc_voidReadADC(CH1,ADC_SampleTime_Cycles_5);

			 inputVoltage1 = (POT*33) / 4096 ;

		}

	}

	/* Loop forever */
	for(;;)
	{
		//LCD_vidClear( );
		STK_voidIntervalSingle(10000-1,ahmed2);
		LCD_vidGotoXY( 1 , '\0' );
		itoa(inputVoltage/10,SHOWLDR,10);

		LCD_vidWriteString("LDR(volt):");
		LCD_vidWriteString(SHOWLDR);
		itoa(inputVoltage%10,SHOWLDR,10);
		LCD_vidWriteString(SHOWLDR);
		LCD_vidWriteString(" V");





		LCD_vidGotoXY( 2 , '\0' );
		itoa(inputVoltage1/10,SHOWPOT,10);

		LCD_vidWriteString("POT(volt):");
		LCD_vidWriteString(SHOWPOT);

		itoa(inputVoltage1%10,SHOWPOT,10);
		LCD_vidWriteString(SHOWPOT);
		LCD_vidWriteString(" V");
		delay_us(100);



	}


}


